### ISSUE TITLE
Not Geting data

### ISSUE THREAD

**Issue by KingRizviAhmmed** [Ansh-Rathod/Flutter-Bloc-Recipe-app#2]
i add api key and run the app .but no data is comming . i see only the text 'somthing wents wrong'

**Comment by Ansh-Rathod** [comment]
Hii

Sorry for the issue you just edit /lib/api/api_key.dart file to
static List<String> keys = ['add your api key here']; 
this to 
static String keys= 'your api key';

And then you will find some error in /repo/ folder just replace all
 ```
apiKey[Random().nextInt(14)]
``` to _apiKey_
In 
home_page_repo.dart
random_food_repo.dart
recipe_information.dart
search_repo.dart

**Comment by Ansh-Rathod** [comment]
now i have updated a repo :)
